name: Android APK (Kivy/Buildozer)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - '**.py'
      - 'buildozer.spec'
      - '.github/workflows/android-build.yml'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker diagnostics
        run: |
          docker --version
          docker info || true

      - name: Pull Buildozer image
        run: docker pull kivy/buildozer:latest

      - name: Build debug APK with Buildozer (Docker)
        run: |
          docker run --rm \
            -v "$PWD":/home/buildozer \
            -w /home/buildozer \
            kivy/buildozer:latest \
            buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: bpm-converter-apk
          path: bin/*.apk
