name: Android APK (Kivy/Buildozer)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - '**.py'
      - 'buildozer.spec'
      - '.github/workflows/android-build.yml'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer Action
        uses: Arthelon/buildozer-action@v1
        with:
          command: android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: bpm-converter-apk
          path: bin/*.apk
